HOSTS:
  ubuntu-server-1404-i386:
    roles:
      - master
    platform: ubuntu-1404-i386
    box: puppetlabs/ubuntu-14.04-32-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-32-nocm
    hypervisor: vagrant

CONFIG:
  log_level: verbose

